{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aws-sigv4-proxy-admission-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-sigv4-proxy-admission-controller.labels" . | indent 4 }}
{{- end -}}