apiVersion: v1
name: appmesh-gateway
description: App Mesh Gateway Helm chart for Kubernetes
version: 0.1.5
appVersion: 1.0.0
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws/eks-charts
maintainers:
  - name: Stefan Prodan
    url: https://github.com/stefanprodan
    email: stefanprodan@users.noreply.github.com
keywords:
  - eks
  - appmesh
  - ingress
  - gateway
