# Default values for appmesh-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: 840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy
  tag: v1.12.3.0-prod
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  # externalTrafficPolicy: when set to Local it preserves the client source IP
  externalTrafficPolicy: Cluster
  # annotations: NLB as default load balancer type
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

appmesh:
  # appmesh.gateway: Whether to create a VirtualGateway or not
  gateway: true
  # appmesh.preview: Whether to enable App Mesh Preview (us-west-2 only) or not
  preview: false

# resources: requests are set by default to enable HPA
resources:
#  limits:
#    cpu: 2000m
#    memory: 1Gi
  requests:
    cpu: 100m
    memory: 64Mi

# podAnnotations: Prometheus scraping is enabled by default
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9901"
  prometheus.io/path: "/stats/prometheus"

# podAntiAffinity: the scheduler should prefer to not schedule
# two replica pods onto the same node but no guarantee is provided.
podAntiAffinity:
  enabled: true

# affinity: node/pod affinity (disable podAntiAffinity to use this)
affinity: {}

nodeSelector: {}

tolerations: []

serviceAccount:
  # serviceAccount.create: Whether to create a service account or not
  create: true
  # serviceAccount.name: The name of the service account to create or use
  name: ""
  annotations: {}

rbac:
  # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
  pspEnabled: false
