apiVersion: v1
name: aws-cloudwatch-metrics
description: A Helm chart to deploy aws-cloudwatch-metrics project
version: 0.0.4
appVersion: "1.247345"
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
- https://github.com/aws/eks-charts
keywords:
- eks
- cloudwatch
- cloudwatch-metrics
- containerinsights
