apiVersion: v1
name: amazon-ec2-metadata-mock
description: A Helm chart for Amazon EC2 Metadata Mock
version: 1.11.2
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws/amazon-ec2-metadata-mock
  - https://github.com/aws/eks-charts/
maintainers:
  - name: pdk27
    url: https://github.com/pdk27
    email: pdk27@users.noreply.github.com
  - name: brycahta
    url: https://github.com/brycahta
    email: brycahta@users.noreply.github.com
keywords:
  - ec2
  - aws-ec2
  - imds
  - ec2-instance-metadata
  - ec2-instance-metadata-mock
  - spot-interruption-mock
  - ec2-rebalance-recommendation
