apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "aws-cloudwatch-metrics.fullname" . }}
  labels:
    {{- include "aws-cloudwatch-metrics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aws-cloudwatch-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aws-cloudwatch-metrics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aws-cloudwatch-metrics.serviceAccountName" . }}
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # Please don't change below envs
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CI_VERSION
          value: "k8s/1.3.9"
        # Please don't change the mountPath
        volumeMounts:
        - name: cwagent-config
          mountPath: /etc/cwagentconfig
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: dockersock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: varlibdocker
          mountPath: /var/lib/docker
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: devdisk
          mountPath: /dev/disk
          readOnly: true
        {{- if .Values.prometheus.enabled }}
        - name: prometheus-config
          mountPath: /etc/prometheusconfig
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: cwagent-config
        configMap:
          name: {{ include "aws-cloudwatch-metrics.fullname" . }}
          items:
          - key: cwagentconfig.json
            path: cwagentconfig.json
      {{- if .Values.prometheus.enabled }}
      - name: prometheus-config
        configMap:
          name: {{ include "aws-cloudwatch-metrics.fullname" . }}
          items:
          - key: prometheus.yaml
            path: prometheus.yaml
      {{- end }}
      - name: rootfs
        hostPath:
          path: /
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: varlibdocker
        hostPath:
          path: /var/lib/docker
      - name: sys
        hostPath:
          path: /sys
      - name: devdisk
        hostPath:
          path: /dev/disk/
      {{- range .Values.additionalConfigVolumes }}
      - name: {{ .name }}
        {{- with .configMap }}
        configMap:
          name: {{ tpl .name $ }}
          {{- with .items }}
          items:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
