apiVersion: v1
name: aws-sigv4-proxy-admission-controller
description: AWS SIGv4 Admission Controller Helm Chart for Kubernetes
version: 0.1.3
appVersion: 1.0
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws/eks-charts
maintainers:
  - name: AWS Observability Team
    url: https://github.com/aws-observability
