---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "aws-load-balancer-controller.namePrefix" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook-service
    {{ include "aws-load-balancer-controller.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "aws-load-balancer-controller.namePrefix" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: metrics-service
    {{- include "aws-load-balancer-controller.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: metrics-server
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
