apiVersion: v1
kind: Service
metadata:
  name: {{ template "aws-load-balancer-controller.namePrefix" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-load-balancer-controller.labels" . | indent 4 }}
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
