{{ if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aws-load-balancer-controller.fullname" . }}
  labels:
    {{- range $key, $value := .Values.metrics.serviceMonitor.selector }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics-service
{{ include "aws-load-balancer-controller.labels" . | indent 6 }}
  endpoints:
  - port: http
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    path: {{ .Values.metrics.serviceMonitor.path }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{ end }}
