kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "amazon-ec2-metadata-mock.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "amazon-ec2-metadata-mock.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "amazon-ec2-metadata-mock.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
