apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "amazon-ec2-metadata-mock.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "amazon-ec2-metadata-mock.labels" . | indent 4 }}