apiVersion: v1
kind: Service
metadata:
  name: {{ template "appmesh-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "appmesh-gateway.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    name: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ template "appmesh-gateway.fullname" . }}
