{{- if .Values.deviceClass.create }}
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: {{ .Values.deviceClass.name }}
  labels:
    {{- include "aws-dranet.labels" . | nindent 4 }}
spec:
  selectors:
  - cel:
      expression: |
        device.driver == "dra.net" &&
        device.attributes["dra.net"].pciDevice == 'Elastic Fabric Adapter (EFA)'
{{- end }}
