{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-dranet.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-dranet.labels" . | nindent 4 }}
{{- end }}
