{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "aws-loadbalancer-controller.fullname" . }}-leader-election-role
  labels:
    {{- include "aws-loadbalancer-controller.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [""]
  resources: [configmaps/status]
  verbs: [get, update, patch]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "aws-loadbalancer-controller.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "aws-loadbalancer-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "aws-loadbalancer-controller.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ template "aws-loadbalancer-controller.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "aws-loadbalancer-controller.fullname" . }}-manager-role
  labels:
    {{- include "aws-loadbalancer-controller.labels" . | nindent 4 }}
rules:
- apiGroups: ["elbv2.k8s.aws", "", "networking.k8s.io"]
  resources: [targetgroupbindings, configmaps, endpoints, events, ingresses, ingresses/status, services, services/status, pods/status]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: ["elbv2.k8s.aws"]
  resources: [targetgroupbindings/status]
  verbs: [get, update, patch]
- apiGroups: [""]
  resources: [nodes, pods, secrets, services, namespaces]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "aws-loadbalancer-controller.fullname" . }}-manager-rolebinding
  labels:
    {{- include "aws-loadbalancer-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "aws-loadbalancer-controller.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "aws-loadbalancer-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
