tls_secret_name: pod-identity-webhook
annotation_prefix: eks.amazonaws.com
token_audience: sts.amazonaws.com

replicas: 3

image:
  repository: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pod-identity-webhook
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 2000m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

priorityClassName: ""

serviceAccount:
  # serviceAccount.create: Whether to create a service account or not
  create: true
  # serviceAccount.name: The name of the service account to create or use
  name: ""
