apiVersion: v1
name: appmesh-inject
description: App Mesh Inject Helm chart for Kubernetes
version: 0.3.0
appVersion: 0.2.0
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws/eks-charts
maintainers:
  - name: Nicholas Turner
    url: https://github.com/nckturner
    email: nckturner@users.noreply.github.com
  - name: Stefan Prodan
    url: https://github.com/stefanprodan
    email: stefanprodan@users.noreply.github.com
keywords:
  - eks
  - appmesh
