apiVersion: v1
kind: Service
metadata:
  name: {{ template "appmesh-spire-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "appmesh-spire-server.name" . }}