apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: eks-connector-activation-config
type: Opaque
data:
  code: {{  .Values.eks.activationCode | print | b64enc }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name:  eks-connector-token
  annotations:
    kubernetes.io/service-account.name:  eks-connector
