apiVersion: v1
appVersion: v1.7.3-debian-cloudwatch-1.0
description: A Fluentd CloudWatch Helm chart for Kubernetes.
engine: gotpl
home: https://www.fluentd.org/
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
keywords:
- fluentd
- cloudwatch
- logging
name: fluentd-cloudwatch
sources:
- https://github.com/fluent/fluentd-kubernetes-daemonset
version: 0.0.1
