image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: v1.7.3-debian-cloudwatch-1.0
## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
  pullPolicy: IfNotPresent

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 200Mi

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
  # kubernetes.io/role: node
# Ref: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#affinity-v1-core
# Expects input structure as per specification for example:
#   affinity:
#     nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: foo.bar.com/role
#            operator: In
#            values:
#            - master
affinity: {}

volumeMounts: []
#   - name: runlogjournal
#     mountPath: /run/log/journal
#     readOnly: true

volumes: []
#   - name: runlogjournal
#     hostPath:
#       path: /run/log/journal

## Add tolerations if specified
tolerations: []
#   - key: node-role.kubernetes.io/master
#     operator: Exists
#     effect: NoSchedule

podSecurityContext: {}

podAnnotations: {}

# Pod priority
# Sets PriorityClassName if defined.
#
# priorityClassName: "my-priority-class"

awsRegion: us-east-1
clusterName: kubernetes
ciVersion: k8s/1.2.4
awsRole:
awsAccessKeyId:
awsSecretAccessKey:

rbac:
  ## If true, create and use RBAC resources
  create: true
  pspEnabled: false

  ## Ignored if rbac.create is true
  serviceAccountName: default
  ## Annotations for the Service Account
  serviceAccountAnnotations: {}
# Add extra environment variables if specified (must be specified as a single line object and be quoted)
extraVars: []
# - "{ name: NODE_NAME, valueFrom: { fieldRef: { fieldPath: spec.nodeName } } }"

busybox:
  repository: busybox
  tag: 1.31.0

config:
  # customise the whole config including setting up fluent.conf
  conf: {}
  dataplane:
    enabled: true
    # customise systemd.conf
    ## conf:
    ##   systemd.conf: |
    ##     <source>
    ##     ..
    conf: {}
  host:
    enabled: true
    # customise host.conf
    ## conf:
    ##   host.conf: |
    ##     <source>
    ##     ..
    conf: {}
  containers:
    # customise containers.conf
    ## conf:
    ##   containers.conf: |
    ##     <source>
    ##     ..
    conf: {}
