{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-for-fluent-bit.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aws-for-fluent-bit.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-for-fluent-bit.fullname" . }}
    namespace: {{ include "aws-for-fluent-bit.namespace" . }}
{{- end -}}
