{{- if $.Values.serviceMonitor }}
{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.serviceMonitor.enabled ) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "aws-for-fluent-bit.labels" . | nindent 4 }}
  name: {{ include "aws-for-fluent-bit.fullname" . }}
  namespace: {{ include "aws-for-fluent-bit.namespace" . }}
spec:
  ports:
  - name: monitor-agent
    port: {{ .Values.serviceMonitor.service.port }}
    protocol: TCP
    targetPort: {{ .Values.serviceMonitor.service.targetPort }}
  selector:
    {{- include "aws-for-fluent-bit.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.serviceMonitor.service.type }}
{{- end }}
{{- end }}
