kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "aws-calico.fullname" . }}-node"
  labels:
    app.kubernetes.io/name: "{{ include "aws-calico.fullname" . }}-node"
{{ include "aws-calico.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods/status
    verbs:
      - patch
  - apiGroups: [""]
    resources:
      - nodes/status
    verbs:
      - patch
      - update
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups: ["extensions"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - watch
      - list
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - globalfelixconfigs
      - felixconfigurations
      - bgppeers
      - globalbgpconfigs
      - bgpconfigurations
      - ippools
      - ipamblocks
      - globalnetworkpolicies
      - globalnetworksets
      - networkpolicies
      - networksets
      - clusterinformations
      - hostendpoints
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - blockaffinities
      - ipamblocks
      - ipamhandles
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - blockaffinities
    verbs:
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "aws-calico.fullname" . }}-node"
  labels:
{{ include "aws-calico.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "aws-calico.fullname" . }}-node"
subjects:
  - kind: ServiceAccount
    name: "{{ include "aws-calico.serviceAccountName" . }}-node"
    namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "aws-calico.fullname" . }}-typha-cpha"
  labels:
{{ include "aws-calico.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  "{{ include "aws-calico.fullname" . }}-typha-cpha"
subjects:
  - kind: ServiceAccount
    name: "{{ include "aws-calico.serviceAccountName" . }}-typha-cpha"
    namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "aws-calico.fullname" . }}-typha-cpha"
  labels:
{{ include "aws-calico.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "aws-calico.fullname" . }}-typha-cpha"
  labels:
{{ include "aws-calico.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["deployments/scale"]
    verbs: ["get", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "aws-calico.fullname" . }}-typha-cpha"
  labels:
{{ include "aws-calico.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "aws-calico.fullname" . }}-typha-cpha"
subjects:
  - kind: ServiceAccount
    name: "{{ include "aws-calico.serviceAccountName" . }}-typha-cpha"
    namespace: "{{ .Release.Namespace }}"
