# Create the ServiceAccount and roles necessary for Calico.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-node
  labels:
    k8s-app: calico-node
{{ include "aws-calico.labels" . | indent 4 }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: typha-cpha
  labels:
    k8s-app: typha-cpha
{{ include "aws-calico.labels" . | indent 4 }}