{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aws-vpc-cni.serviceAccountName" . }}
{{- with .Values.serviceAccountAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
{{- end -}}
