{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aws-vpc-cni.serviceAccountName" . }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
{{- end -}}
