{{- if.Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aws-vpc-cni.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.serviceMonitor.namespace }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
  {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "aws-vpc-cni.labels" . | indent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
    {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.scrapeTimeout  }}
      scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
