{
 "title": "AWS App Mesh: Control Plane",
 "description": "AWS App Mesh control plane overview",
 "tags": [ "appmesh" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Control Plane API Requests Duration By Operation",
   "type": "graph",
   "description": "appmesh-controller-manager API requests duration per second ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aws_api_request_duration_seconds_count[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Control Plane API Requests",
   "type": "graph",
   "description": "appmesh-controller-manager API request count by operation",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aws_api_requests_total[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Control Plane API Requests Retries By Operation",
   "type": "graph",
   "description": "appmesh-controller-manager API requests retries by operation",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aws_api_call_retries_count[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "appmesh-system containers memory working set",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"appmesh-system\",container_name!=\"POD\",container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "appmesh-system containers CPU usage seconds total",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"appmesh-system\",container_name!=\"POD\",container_name!=\"\"}[1m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}