{
 "title": "AWS App Mesh: Control Plane",
 "description": "AWS App Mesh control plane overview",
 "tags": [ "appmesh" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API",
   "type": "singlestat",
   "description": "App Mesh control plane operations per second",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(appmesh_api_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Meshes",
   "type": "singlestat",
   "description": "App Mesh instances present on this cluster",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(appmesh_mesh_state)" }
   ]
  },
  {
   "title": "Virtual Services",
   "type": "singlestat",
   "description": "App Mesh virtual services present on this cluster",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(appmesh_virtual_service_state)"
    }
   ]
  },
  {
   "title": "Virtual Nodes",
   "type": "singlestat",
   "description": "App Mesh virtual nodes present on this cluster",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(appmesh_virtual_node_state)"
    }
   ]
  },
  {
   "title": "Control Plane API Requests",
   "type": "graph",
   "description": "appmesh-controller API requests per second ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(appmesh_api_request_duration_seconds_count[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "appmesh-system containers memory working set",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"appmesh-system\",container_name!=\"POD\",container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "appmesh-system containers CPU usage seconds total",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"appmesh-system\",container_name!=\"POD\",container_name!=\"\"}[1m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}