{
 "title": "AWS App Mesh: Data Plane",
 "description": "AWS App Mesh data plane overview",
 "tags": [ "appmesh" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Envoy Sidecars",
   "type": "singlestat",
   "description": "Total number of App Mesh sidecars",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_server_live{job=\"appmesh-envoy\"})",
     "legendFormat": "Total Envoy sidecars"
    }
   ]
  },
  {
   "title": "Unhealthy Sidecars  ",
   "type": "singlestat",
   "description": "Unhealthy App Mesh Envoy instances",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy{job=\"appmesh-envoy\"})  - sum(envoy_cluster_membership_total{job=\"appmesh-envoy\"}))",
     "legendFormat": "Unhealthy sidecars"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "App Mesh sidecars total inbound connections",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{job=\"appmesh-envoy\"})",
     "legendFormat": "Total connections"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "description": "App Mesh in/out traffic",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{job=\"appmesh-envoy\"}[1m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{job=\"appmesh-envoy\"}[1m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Envoy Requests by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy requests per second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{job=\"appmesh-envoy\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Envoy 2xx Requests by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy success HTTP requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{job=\"appmesh-envoy\",envoy_response_code=~\"2.*\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}} 5xx"
    }
   ]
  },
  {
   "title": "Envoy 5xx/4xx Requests by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy failed HTTP requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{job=\"appmesh-envoy\",envoy_response_code=~\"5.*\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}} 5xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{job=\"appmesh-envoy\",envoy_response_code=~\"4.*\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}} 4xx"
    }
   ]
  },
  {
   "title": "Envoy Memory Usage by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy sidecar containers memory working set by namespace",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"envoy\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Envoy CPU Usage by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy sidecar containers CPU usage seconds total",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container=\"envoy\"}[1m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Connection Timeout by Namespace",
   "type": "graph",
   "description": "Total connection connect timeouts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Request Timeout by Namespace",
   "type": "graph",
   "description": "Total requests that timed out waiting for a response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  }
 ]
}