
imagePullSecrets: []

image:
  repository: public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws
  tag: 1.0.r2-2021.08.13.20.34-linux-amd64
  pullPolicy: IfNotPresent

nodeSelector: {}
tolerations: []
env: {}

#Example
#env:
#    http_proxy: http://proxyserver:3128
#    https_proxy: http://proxyserver:3128
#    no_proxy: "localhost,127.0.0.1,.cluster.local"

port: 8989

privileged: false

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

podLabels: {}
podAnnotations: {}

updateStrategy:
  type: RollingUpdate

secrets-store-csi-driver:
  install: false

## Install default service account
rbac:
  install: true
  pspEnabled: false
  serviceAccount:
    name:
