apiVersion: v1
kind: Service
metadata:
  name: {{ template "appmesh-manager.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "appmesh-manager.labels" . | indent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: {{ template "appmesh-manager.fullname" . }}
