{{- if .Values.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "sscdpa.psp.fullname" . }}-role-binding
  namespace: {{ .Release.Namespace }}
{{ include "sscdpa.labels" . | indent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "sscdpa.psp.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "sscdpa.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
