{{- if .Values.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "sscdpa.psp.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
{{ include "sscdpa.labels" . | indent 2 }}
rules:
  - apiGroups: [ 'policy' ]
    resources: [ 'podsecuritypolicies' ]
    verbs: [ 'use' ]
    resourceNames:
      - {{ template "sscdpa.psp.fullname" . }}
{{- end }}
