name: CI
on:
  pull_request:
    paths:
      - "**/*.tpl"
      - "**/*.yaml"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.repository == 'aws/eks-charts'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
      - run: make install-toolchain
      - run: make verify
      - run: make package
