name: CI
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.repository == 'aws/eks-charts'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
      - run: make install-toolchain
      - run: make verify
      - run: make package
