name: push
on:
  push:
    branches-ignore:
      - gh-pages
    tags-ignore:
      - test*
env:
  AWS_REGION: us-east-1
  AWS_ROLE: arn:aws:iam::585529207810:role/terraform-20221013163558416000000001
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # we need to fetch tags, and not just the tags on our commit
          # so we cannot get by with a shallow checkout
          fetch-depth: 0
      - uses: actions/setup-go@v3
      - name: Install Toolchain
        run: make install-toolchain
      # we package BEFORE running lint unlike upstream
      # this is due to an error that upstream seems to also have, but are ignoring:
      # Error: An error occurred while checking for chart dependencies.
      # You may need to run `helm dependency build` to fetch missing dependencies:
      # found in Chart.yaml, but missing in charts/ directory: secrets-store-csi-driver
      - name: Package stable charts
        run: make package
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: eks-charts
          aws-region: ${{ env.AWS_REGION}
      - name: Lint and Validate Charts w/ helm v2 and v3
        run: |
          make verify
      - name: Publish stable charts
        run: aws kms list-keys
  e2e-helm:
    needs: build-test-push
    strategy:
      matrix:
        helm: [v2, v3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Toolchain
        run: make install-toolchain
      - name: Init Kubernetes Kind and Helm vX
        run: HELM_MODE=${{ matrix.helm}} test/lib/kind.sh
      - name: Run App Mesh tests
        run: test/run.sh
