name: push
on:
  push:
    branches-ignore:
      - gh-pages
    tags-ignore:
      - test*
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Install Toolchain
        run: make install-toolchain 
      - name: Lint and Validate Charts w/ helm v2 and v3
        run: |
          make verify
      - name: Package stable charts
        run: make package
      - name: Publish stable charts
        run: make publish
  e2e-helm:
    needs: build-test-push
    strategy:
      matrix:
        helm: [v2, v3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Toolchain
        run: make install-toolchain 
      - name: Init Kubernetes Kind and Helm vX
        run: HELM_MODE=${{ matrix.helm}} test/lib/kind.sh
      - name: Run App Mesh tests
        run: test/run.sh
